#!/bin/bash

# general terminal aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias env='env | sort'
alias grep='grep -n'
alias howbig='du -csh '$@''
alias wat='whoami && hostname'
alias sfind='sudo find / -name '$@''
alias gs='git status'
alias please='sudo env 'PATH=$PATH' '$@''

# ssh shortcuts
alias nero='ssh -X josh@nero'
alias nerotunnel='ssh -L 8888:localhost:8888 josh@nero'
alias galba='ssh josh@galba'
alias galbatunnel='ssh -L 8890:localhost:8890 josh@galba'
alias slac7='ssh josh@centos7.slac.stanford.edu'
