#!/bin/bash

# general terminal aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lesss='less -RSI +G'
alias colorize="perl $PWD/colorize/colorize"
alias env='env | sort'

# personal terminal shortcuts
alias wat='whoami && hostname'
alias sfind='sudo find / -name '$@''
alias sz='sudo zypper '$@''

# multi-media shortcuts
alias rpa='pulseaudio --kill && pulseaudio --start'
alias plex='docker start plex'
alias leaper='docker start leaper && docker attach leaper'
alias pynb='jupyter notebook --no-browser'
alias ps3='cd ~/Programs/rpcs3 && ./rpcs3-*_linux64.AppImage'
alias ps3upd='cd ~/Programs/rpcs3 && ./ps3.sh'

# ssh shortcuts
alias nerotunnel='ssh -L 8888:localhost:8888 josh@nero'
alias nero='ssh -X josh@nero'
alias galba='ssh josh@galba'
alias galbatunnel='ssh -L 8890:localhost:8890 josh@galba'
alias triumf01='ssh josh@dcrc01.triumf.ca'
