#!/bin/bash

# Colorize
color_prompt=yes

# Activate colorization for less
export LESSOPEN="|$PWD/lesspipe/lesspipe.sh %s"

# Link colorize config to the expected place
[ -h "$HOME/.colorizerc" ] || ln -sfv "$PWD/colorize/colorizerc" "$HOME/.colorizerc"

# Set up color profile
if eval $(dircolors "$PWD/dircolors/dircolors.256dark") ; then
  alias ls='ls --color=always'
  alias grep='grep --color=always'
fi &> /dev/null
