#!/bin/bash

# Colorize
color_prompt=yes

# Activate colorization for less
export LESSOPEN="|$PWD/lesspipe/lesspipe.sh %s"

# Link colorize config to the expected place
[ -h "$HOME/.colorizerc" ] || ln -sfv "$PWD/colorize/colorizerc" "$HOME/.colorizerc"
