#!/usr/bin/env bash

# ls after cd 
function cs() {
    cd "$@" && ls -al
}

# git some file
function git_file_gl() {
	# Arguments:
	# 1. the numeric project ID 
	# 2. the file you want (incl. ext)
	# 3. the branch to pull from
 
	curl --header "Private-Token: ${GITLAB_TOKEN}" "https://gitlab.com/api/v4/projects/$1/repository/files/$2/raw\?ref\=$3"
}