#!/usr/local/bin/bash

export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/Cellar:/usr/local/bin:/usr/local/sbin:$PATH
export MANPATH=/opt/local/share/man:$MANPATH
export DISPLAY=:0.0
export HOMEBREW_GITHUB_API_TOKEN="bac60908e24c79caf3acc1a690a778b0c22535f2"

eval "$(pyenv init -)"

# ~/.dircolors/themefile
eval $(gdircolors "$PWD/dircolors/dircolors.256dark")

# Aliases
alias ls='gls --color=auto'
alias ll='ls -al'
alias bash='/usr/local/bin/bash'
